feat: add serviceAccount and extraVolumes
bman46/CTFd-Helm pull request #37
Opened 2023-08-31 15:05 UTC by thibaultserti

2023-08-31 15:54 UTC, bman46 commented
Is this still a draft?

2023-08-31 15:58 UTC, bman46 requested changes

2023-08-31 15:58 UTC, bman46 commented on values.yaml
> +  create: true
Should this be defaulted to false?

2023-09-02 19:39 UTC, thibaultserti commented
Yes

2023-09-04 18:10 UTC, thibaultserti commented
In fact, I need to change many things to make it work for me. I don't have much time in the next few days, I'll try to do this when I can free some time.

2023-09-04 18:20 UTC, bman46 commented
All good. Just mark this PR as ready when you get time to complete it and I'll review it.

2025-02-11 15:03 UTC, closed without merging